version: '3.9'

services:
  app:
    image: node:18
    volumes:
      - type: bind
        source: ./app
        target: /app
    working_dir: /app
    ports:
      - '3000:3000'
    tty: true
    command: npm run dev

  api:
    build:
      context: _docker/api
      dockerfile: Dockerfile
    volumes:
      - type: bind
        source: ./api
        target: /app
    working_dir: /app
    ports:
      - '3001:3001'
    tty: true
